//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonement()
        {
            this.Uchet = new HashSet<Uchet>();
        }
    
        public int ID_abonement { get; set; }
        public Nullable<System.DateTime> Date_start { get; set; }
        public Nullable<System.DateTime> Date_finish { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Trener { get; set; }
        public Nullable<int> Count_trens { get; set; }
        public Nullable<int> ID_trener { get; set; }
        public Nullable<int> ID_typeAb { get; set; }
        public Nullable<int> ID_zal { get; set; }
    
        public virtual Trener Trener1 { get; set; }
        public virtual TypeAbon TypeAbon { get; set; }
        public virtual Zal Zal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchet> Uchet { get; set; }
    }
}
