//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int id_card { get; set; }
        public Nullable<int> number_card { get; set; }
        public string date { get; set; }
        public string vladelec { get; set; }
        public Nullable<int> cvc { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
