//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchet
    {
        public int ID_client { get; set; }
        public int ID_abonement { get; set; }
        public Nullable<decimal> Date_price { get; set; }
        public Nullable<int> Activ_days { get; set; }
    
        public virtual Abon Abon { get; set; }
        public virtual Client Client { get; set; }
    }
}
